services:
  postgres:
    image: postgres:16
    container_name: fraud_pg
    environment:
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraudpass
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: fraud_mb
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

volumes:
  pgdata:
  metabase_data:
